export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
      

    
      {children}
      <div>FOOTER DE index</div></body>
    </html>
  )
}
